### ISSUE TITLE
React js warning after save

### ISSUE THREAD

**Issue by rgnevashev** [nicolaslopezj/simple-react-form#24] opened 2016-08-25 07:19 UTC
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Form component.

**Comment by nicolaslopezj** [comment] 2016-08-25 15:48
Is this duplicate of #4?

**Comment by rgnevashev** [comment] 2016-08-25 15:58
yep. i have got same error. ver 1.6.10

**Comment by nicolaslopezj** [comment] 2016-08-25 16:08
Ok, I'm going to check

**Comment by nicolaslopezj** [comment] 2016-09-08 18:35
I think this issue is fixed, if you are still having this error it could be your app

**Closed by nicolaslopezj** 2016-09-08 18:35 UTC
